### PR TITLE
fix: 🐛 Set `txHash` before setting transaction status to `Running`

### PR DESCRIPTION
**Pull request by prashantasdeveloper**

### CODE REVIEW

**Review by polymath-eric — APPROVED** [review]
LGTM

**Review by VictorVicente — APPROVED** [review]

**Review by VictorVicente — COMMENTED** [review]
Approved, but is this being tested anywhere? Is it possible to add a test checking that txHash is present when `TransactionStatus.Running` is set?

**Comment by monitz87** [comment]
> Approved, but is this being tested anywhere? Is it possible to add a test checking that txHash is present when `TransactionStatus.Running` is set? 

Agreed. This should be tested. I think it's possible (not at my computer right now)

**Pull request merged**
