### PR TITLE
feat: 🎸 Add reserved to AccountBalance

### PR DESCRIPTION
**Pull request by polymath-eric**

### CODE REVIEW

**Review by monitz87 — CHANGES_REQUESTED** [review]
`reserved` shouldn't really be exposed, since it doesn't have a use in the chain and as such it will just confuse users. If it ever becomes a thing, we'll add it. For now we're just adding it to the total to avoid a potential bug in a way that doesn't clutter the interface

**Review by monitz87 — APPROVED** [review]

**Review by prashantasdeveloper — COMMENTED** [review]
LGTM

**Pull request merged**
