### PR TITLE
fix: 🐛 Explictly check claim type in isScopedClaim typeguard

### PR DESCRIPTION
**Pull request by polymath-eric**
Before isScopedClaim would only check for `scope` field being defined,
which allowed for incorrectly defined claims to pass the check

### CODE REVIEW

**Review by monitz87 — CHANGES_REQUESTED** [review]
There's a linting error. LGTM otherwise

**Comment by polymath-eric** [comment]
Fixed. Weird it was in an untouched file though. 

I am guessing it got added in from a beta to alpha merge. Not sure how else it would slip through since we need feature branches to be at the head of alpha.

**Review by prashantasdeveloper — APPROVED** [review]
LGTM

**Review by monitz87 — APPROVED** [review]

**Pull request merged**
