### PR TITLE
feat: 🎸 Add createMultiSig procedure

### PR DESCRIPTION
**Pull request by polymath-eric**
Adds createMultiSig procedure into AccountManagement

### CODE REVIEW

**Comment by polymath-eric** [comment]
I am not sure why sonar cloud think `this` is being unused when I copied the format from other procedures. It does seem weird to have a function parameter that shadows this.

I am tempted to mark it as not an issue since there seems to be precedence for this. Not sure if I am missing something though.

**Review by prashantasdeveloper — CHANGES_REQUESTED** [review]
Left some nit comments about renaming and docs

**Comment by prashantasdeveloper** [comment]
> I am not sure why sonar cloud think `this` is being unused when I copied the format from other procedures. It does seem weird to have a function parameter that shadows this.
> 
> I am tempted to mark it as not an issue since there seems to be precedence for this. Not sure if I am missing something though.

I have also wondered about why we use the `this` param, felt kind of odd. I'm also not sure, if something is wrong but could you try importing `MultiSig` from `~/internal` instead of `~/api/entites/MultiSig`? If that doesn't work maybe Jere can help us out here

**Review by prashantasdeveloper — APPROVED** [review]
LGTM. But still not sure why sonar is not giving the pass on the `this` thing.

**Comment by polymath-eric** [comment]
@monitz87 let me know what you think about the code smell when you review this

**Pull request merged**
