### PR TITLE
Alpha into beta

### PR DESCRIPTION
**Pull request by polymath-eric**
### Description

Merge the latest alpha changes into beta

### CODE REVIEW

**Comment by polymath-eric** [comment]
There are 12 code smells, but its for deprecated calls and changing the autogen files from polkadot.js

I think we should ignore the smells for this PR. We might want to change the deprecated stuff in a later PR, but I figure we can put it off until the deprecated becomes breaking.

**Review by VictorVicente — APPROVED** [review]

**Pull request merged**
