### PR TITLE
Feat/msdk 358 add pagination support

### PR DESCRIPTION
**Pull request by shuffledex**

### CODE REVIEW

**Review by monitz87 — CHANGES_REQUESTED** [review]

**Comment by shuffledex** [comment]
if I remove createQueryStub in the suggested changes, the tests fails

**Review by monitz87 — APPROVED** [review]

**Comment by monitz87** [comment]
> if I remove createQueryStub in the suggested changes, the tests fails

You're right. Fix the code smell and you can merge

**Review by monitz87 — APPROVED** [review]

**Comment by VictorVicente** [comment]
This PR includes breaking changes. @shuffledex Please, add the commit to indicate it and a brief explanation of them in the PR description.

**Comment by shuffledex** [comment]
> This PR includes breaking changes. @shuffledex Please, add the commit to indicate it and a brief explanation of them in the PR description.

its already there! https://github.com/PolymathNetwork/polymesh-sdk/pull/343/commits/60532ced6335cbe85867edae6db5c89be27bf5a8

**Pull request merged**
