### PR TITLE
chore: 🤖 Remove redundant expiry date check

### PR DESCRIPTION
**Pull request by prashantasdeveloper**
#### JIRA Link

https://polymath.atlassian.net/browse/MSDK-774

#### Changelog 

Removed the redundant expiry date check from `modifyDistributionCheckpoint` procedure and updated the validation message for paymentDate validation to _“Cannot modify a Distribution checkpoint after the payment date”_

### CODE REVIEW

**Comment by prashantasdeveloper** [comment]
@monitz87 please review

**Review by monitz87 — APPROVED** [review]

**Pull request merged**
