### PR TITLE
adds cdd claim type

### PR DESCRIPTION
**Pull request by hlminh2000**
Addressing this convo: https://polymathnetwork.slack.com/archives/GL43F3BRN/p1611179577060000
- please advice if `CddClaim` is an appropriate name

https://polymath.atlassian.net/browse/MSDK-436

### CODE REVIEW

**Comment by VictorVicente** [comment]
It looks good to me. Congrats @hlminh2000. Just a comment, we use `alpha` branch for development so I rebased your PR to this branch. I also added the same mechanism to `getInvestorUniquenessClaims`. 
I asked @shuffledex to review the PR as well before merge it.
Thanks for your contribution!

**Review by VictorVicente — APPROVED** [review]

**Review by shuffledex — APPROVED** [review]
Looks good!

**Comment by hlminh2000** [comment]
Thanks for the info @VictorVicente ! Am I clear to merge? Just wanna make sure I follow your process :)

**Pull request merged**
