### PR TITLE
feat: 🎸 MSDK-756 Change `totalSupply` to `initialSupply` on asset creation

### PR DESCRIPTION
**Pull request by prashantasdeveloper**
BREAKING CHANGE: 🧨 `TickerReservation.createToken` now takes `initialSupply` instead of
`totalSupply` parameter for specifying amount of tokens that will be
minted on creation

### CODE REVIEW

**Review by polymath-eric — APPROVED** [review]
LGTM

I think this name makes it a lot more clear what the value is for.

**Review by monitz87 — APPROVED** [review]

**Pull request merged**
