### PR TITLE
feat: 🎸 Move createVenue into settlements namespace

### PR DESCRIPTION
**Pull request by polymath-eric**
sdk.currentIdentity.createVenue -> sdk.settlements.createVenue

BREAKING CHANGE: 🧨 createVenue moved from currentIdentity to settlements

### CODE REVIEW

**Review by prashantasdeveloper — COMMENTED** [review]
LGTM

**Comment by polymath-eric** [comment]
@monitz87 Prashant gave an approval for this one.

**Review by prashantasdeveloper — APPROVED** [review]

**Review by monitz87 — APPROVED** [review]

**Pull request merged**
