### PR TITLE
Msdk 831 improve alpha quality

### PR DESCRIPTION
**Pull request by polymath-eric**

### CODE REVIEW

**Comment by polymath-eric** [comment]
the if statement was getting +4 for being so nested, by bringing it up a level it should only get a +2 for nesting, which brings the total to the allowed 15 score.

There is also a similar comparator function in `getMissingPortfolioPermissions` below, so in some sense its a bit more consistent also.

Screen Shot 2022-03-04 at 1 59 37 PM

**Review by monitz87 — APPROVED** [review]

**Pull request merged**
